[tool.poetry]
name = "event_enrichment"
version = "0.1.0"
description = ""
authors = ["Daniel Adler <daniela@cyera.io>"]
readme = "README.md"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
